version: '3.8'

services:
  # PHP Service
  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network

  # MySQL Service
  mysql:
    container_name: mysql
    image: mysql:8.3.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: bot7db
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

  # Nginx Service
  nginx:
    image: nginx:1.25.4-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - .:/var/www/html
    depends_on:
      - php
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql_data:
